vim.g.mapleader = " "
vim.g.maplocalleader = " "
vim.opt.completeopt = { "menuone", "noselect" }
vim.opt.expandtab = true
vim.opt.shiftround = true
vim.opt.shiftwidth = 4
vim.opt.softtabstop = -1
vim.opt.tabstop = 8
vim.opt.textwidth = 80
vim.opt.title = true
vim.opt.fixendofline = false
vim.opt.startofline = false
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.laststatus = 3
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.signcolumn = "yes"
vim.opt.cursorlineopt = "number"
vim.opt.mouse = "a"
vim.opt.updatetime = 1000
vim.opt.termguicolors = true
vim.opt.background = "dark"
vim.opt.clipboard = "unnamedplus"
